# Phase 3: Robust Generalization & Stability Run
model_name: swin_tiny_patch4_window7_224
pretrained: true
freeze_backbone: false
image_size: 224

# Regularization
dropout: 0.4
label_smoothing: 0.1
use_amp: true
ema_decay: 0.9999
use_swa: false

# Focal Loss 
use_focal_loss: true
focal_gamma: 1.5
focal_alpha: 0.75

# Data & Sampling
data_root: data/standardized_jpg
hard_cases_dir: data/hard_cases_web
augmented: true
enable_quality_balance: true
upsample_hard_cases_factor: 6.0
late_upsample_epoch: 4
late_upsample_factor: 7.0

# MixUp/CutMix & Aug knobs for trainer
use_mixup: true
mixup_alpha: 0.2
use_cutmix: true
cutmix_alpha: 1.0

# Optim & Schedule
use_adamw: true
use_lookahead: true
epochs: 8
batch_size: 32
learning_rate: 3e-4      # head lr
backbone_lr: 3e-5         # backbone lr
head_lr: 3e-4
weight_decay: 0.05
min_lr: 1e-6
head_warmup_epochs: 2
head_warmup_lr: 1e-3
scheduler: cosine_warm_restarts
reduce_on_plateau: true
reduce_factor: 0.5
reduce_patience: 2
reduce_min_lr: 1e-6
clip_grad: 1.0

# Early stopping
early_stopping_patience: 3

# Resume/init
resume_training: true
init_from_path: models/regularized_finetune/model_swin_t_regularized.pth

# Output
save_dir: models/final_phase3
checkpoint_path: models/final_phase3/model_swin_t_final.pth

# Dataloader
num_workers: 0
use_class_weights: false
